apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-test
# test it without a namespace.. will argocd put it into the given one anyways? since we created a namespace for this "app"?
# => "works".. it is placed within the namespace given by that created app!
#  namespace: just-testing
# test another namespace, what will happen then?
# a namespace which does not exist is not being created.. test an already existing though..
# => using any existing workspace works.
#  namespace: default

# results..
# so.. adding no namespace will add it into the given one by the app-creation.
# using a non-existing will not work and abort the sync-process.
# using any existing one will just use that one!
  labels:
    app: alpine-test
spec:
  selector:
    matchLabels:
      app: alpine-test
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine-test
    spec:
      containers:
        - name: alpine-test
          image: alpine:latest
          # Just spin & wait forever
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do echo 'hi' && sleep 30; done;" ]
