apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
  namespace: just-testing
  labels:
    app: ubuntu-test
spec:
  selector:
    matchLabels:
      app: ubuntu-test
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
        - name: ubuntu-test
          image: ubuntu:latest
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
